{
    "checksum": "13a4a4374117737d20daffd421702b18514ae6175deda14d9ec429035ecd6d4e",
    "file": "setup.py",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/x-python"
    },
    "number_of_duplicates": 1,
    "package": "azure-kusto-python",
    "path": "azure-kusto-python/1.0.3-1/.pc/0001-Restore-compatibility-with-dateutil-2.7.x.patch/azure-kusto-data/setup.py",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/azure-kusto-python/1.0.3-1/",
        "metric": {
            "size": 616
        },
        "pts_link": "https://tracker.debian.org/pkg/azure-kusto-python",
        "sloc": [
            [
                "python",
                3871
            ],
            [
                "sh",
                10
            ],
            [
                "makefile",
                6
            ]
        ],
        "suites": [
            "bookworm",
            "bullseye",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/python-team/packages/azure-kusto-python",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/a/azure-kusto-python/1.0.3-1/.pc/0001-Restore-compatibility-with-dateutil-2.7.x.patch/azure-kusto-data/setup.py",
    "stat": {
        "perms": "rw-r--r--",
        "size": 1660,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "1.0.3-1"
}