{
    "content": [
        {
            "hidden": false,
            "name": "smtpd.py",
            "stat": {
                "perms": "rw-r--r--",
                "size": 6369,
                "symlink_dest": null,
                "type": "-"
            },
            "type": "file"
        }
    ],
    "directory": "tests",
    "package": "aiosmtplib",
    "path": "aiosmtplib/1.1.4-1/.pc/0001-tests-smtpd-Return-an-error-when-auth-is-called-with.patch/tests",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/aiosmtplib/1.1.4-1/",
        "metric": {
            "size": 488
        },
        "pts_link": "https://tracker.debian.org/pkg/aiosmtplib",
        "sloc": [
            [
                "python",
                4959
            ],
            [
                "makefile",
                22
            ],
            [
                "sh",
                6
            ]
        ],
        "suites": [
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/python-team/packages/aiosmtplib",
        "vcs_type": "git"
    },
    "type": "directory",
    "version": "1.1.4-1"
}