{
    "content": [
        {
            "hidden": false,
            "name": "_converters.py",
            "stat": {
                "perms": "rw-r--r--",
                "size": 1023,
                "symlink_dest": null,
                "type": "-"
            },
            "type": "file"
        }
    ],
    "directory": "data",
    "package": "azure-kusto-python",
    "path": "azure-kusto-python/1.0.3-1/.pc/0001-Restore-compatibility-with-dateutil-2.7.x.patch/azure-kusto-data/azure/kusto/data",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/azure-kusto-python/1.0.3-1/",
        "metric": {
            "size": 616
        },
        "pts_link": "https://tracker.debian.org/pkg/azure-kusto-python",
        "sloc": [
            [
                "python",
                3871
            ],
            [
                "sh",
                10
            ],
            [
                "makefile",
                6
            ]
        ],
        "suites": [
            "bookworm",
            "bullseye",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/python-team/packages/azure-kusto-python",
        "vcs_type": "git"
    },
    "type": "directory",
    "version": "1.0.3-1"
}