{
    "checksum": "f893ef7b80ce11666920d0bf96dc57398af86a0d87aff6552ee2edea5cd06a5c",
    "file": "update_failure_list.py",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/x-python"
    },
    "number_of_duplicates": 13,
    "package": "autofdo",
    "path": "autofdo/0.19-2/third_party/protobuf/conformance/update_failure_list.py",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/autofdo/0.19-2/",
        "metric": {
            "size": 1248592
        },
        "pts_link": "https://tracker.debian.org/pkg/autofdo",
        "sloc": [
            [
                "cpp",
                436213
            ],
            [
                "java",
                108653
            ],
            [
                "objc",
                108251
            ],
            [
                "ansic",
                77107
            ],
            [
                "python",
                45387
            ],
            [
                "cs",
                24942
            ],
            [
                "sh",
                16011
            ],
            [
                "php",
                15368
            ],
            [
                "ruby",
                6255
            ],
            [
                "makefile",
                5807
            ],
            [
                "xml",
                2571
            ],
            [
                "pascal",
                388
            ],
            [
                "lisp",
                182
            ]
        ],
        "suites": [
            "bookworm",
            "bullseye",
            "sid"
        ]
    },
    "raw_url": "/data/main/a/autofdo/0.19-2/third_party/protobuf/conformance/update_failure_list.py",
    "stat": {
        "perms": "rwxr-xr-x",
        "size": 2898,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "0.19-2"
}