{
    "checksum": "6a954a3b5afd1e358652258d5d9e6c255e2aff6382e89face7bb3df77f65e7b0",
    "file": "sidlx_rmi_NetworkUnreachableException_Module.c",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/x-c"
    },
    "number_of_duplicates": 2,
    "package": "babel",
    "path": "babel/1.4.0.dfsg-8.1/runtime/python/sidlx/rmi/sidlx_rmi_NetworkUnreachableException_Module.c",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/babel/1.4.0.dfsg-8.1/",
        "metric": {
            "size": 64556
        },
        "pts_link": "https://tracker.debian.org/pkg/babel",
        "sloc": [
            [
                "ansic",
                628381
            ],
            [
                "java",
                94351
            ],
            [
                "sh",
                31700
            ],
            [
                "f90",
                17373
            ],
            [
                "cpp",
                12095
            ],
            [
                "fortran",
                9197
            ],
            [
                "python",
                8451
            ],
            [
                "makefile",
                6216
            ],
            [
                "perl",
                232
            ],
            [
                "xml",
                118
            ],
            [
                "awk",
                11
            ]
        ],
        "suites": [
            "wheezy"
        ]
    },
    "raw_url": "/data/main/b/babel/1.4.0.dfsg-8.1/runtime/python/sidlx/rmi/sidlx_rmi_NetworkUnreachableException_Module.c",
    "stat": {
        "perms": "rw-r--r--",
        "size": 138169,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "1.4.0.dfsg-8.1"
}