{
    "checksum": "815e3c9fbc2350f6ac6c79001896ea7b9f33c9e0a499243fa291781f5c351d1d",
    "file": "errors.py",
    "mime": {
        "encoding": "utf-8",
        "type": "text/x-python"
    },
    "number_of_duplicates": 2,
    "package": "azure-cosmos-python",
    "path": "azure-cosmos-python/3.1.1-4/azure/cosmos/errors.py",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/azure-cosmos-python/3.1.1-4/",
        "metric": {
            "size": 1268
        },
        "pts_link": "https://tracker.debian.org/pkg/azure-cosmos-python",
        "sloc": [
            [
                "python",
                11654
            ],
            [
                "makefile",
                155
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/python-team/packages/azure-cosmos-python",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/a/azure-cosmos-python/3.1.1-4/azure/cosmos/errors.py",
    "stat": {
        "perms": "rw-r--r--",
        "size": 2421,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "3.1.1-4"
}