{
    "checksum": "f367ac368ba447d4cd5c0042905cf6587f93857ca0d83ac0e259fe36f357042d",
    "file": "key_vault_error_py3.py",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/x-python"
    },
    "number_of_duplicates": 1,
    "package": "azure-cli",
    "path": "azure-cli/2.18.0-2/src/azure-cli/azure/cli/command_modules/keyvault/vendored_sdks/azure_keyvault_t1/v7_2/models/key_vault_error_py3.py",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/azure-cli/2.18.0-2/",
        "metric": {
            "size": 631860
        },
        "pts_link": "https://tracker.debian.org/pkg/azure-cli",
        "sloc": [
            [
                "python",
                272023
            ],
            [
                "sh",
                963
            ],
            [
                "makefile",
                305
            ],
            [
                "javascript",
                34
            ],
            [
                "cs",
                29
            ],
            [
                "xml",
                16
            ],
            [
                "cpp",
                12
            ]
        ],
        "suites": [
            "bookworm",
            "bullseye",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/python-team/packages/azure-cli",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/a/azure-cli/2.18.0-2/src/azure-cli/azure/cli/command_modules/keyvault/vendored_sdks/azure_keyvault_t1/v7_2/models/key_vault_error_py3.py",
    "stat": {
        "perms": "rw-r--r--",
        "size": 1488,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "2.18.0-2"
}