{
    "checksum": "eac6fa63d0c94c69ba054b500825a9c4edd243171ee378fca8a46e55911ac1d9",
    "file": "exceptions.py",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/x-python"
    },
    "number_of_duplicates": 2,
    "package": "azure-data-lake-store-python",
    "path": "azure-data-lake-store-python/0.0.52-1/azure/datalake/store/exceptions.py",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/azure-data-lake-store-python/0.0.52-1/",
        "metric": {
            "size": 31968
        },
        "pts_link": "https://tracker.debian.org/pkg/azure-data-lake-store-python",
        "sloc": [
            [
                "python",
                4571
            ],
            [
                "makefile",
                193
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/python-team/packages/azure-data-lake-store-python",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/a/azure-data-lake-store-python/0.0.52-1/azure/datalake/store/exceptions.py",
    "stat": {
        "perms": "rw-r--r--",
        "size": 855,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "0.0.52-1"
}